
package at.ac.tuwien.dsg.scucrowd.middleware.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MiddlewareWSService", targetNamespace = "http://api.middleware.scucrowd.dsg.tuwien.ac.at/", wsdlLocation = "http://localhost:8080/Middleware?wsdl")
public class MiddlewareWSService
    extends Service
{

    private final static URL MIDDLEWAREWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MIDDLEWAREWSSERVICE_EXCEPTION;
    private final static QName MIDDLEWAREWSSERVICE_QNAME = new QName("http://api.middleware.scucrowd.dsg.tuwien.ac.at/", "MiddlewareWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Middleware?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MIDDLEWAREWSSERVICE_WSDL_LOCATION = url;
        MIDDLEWAREWSSERVICE_EXCEPTION = e;
    }

    public MiddlewareWSService() {
        super(__getWsdlLocation(), MIDDLEWAREWSSERVICE_QNAME);
    }

    public MiddlewareWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MIDDLEWAREWSSERVICE_QNAME, features);
    }

    public MiddlewareWSService(URL wsdlLocation) {
        super(wsdlLocation, MIDDLEWAREWSSERVICE_QNAME);
    }

    public MiddlewareWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MIDDLEWAREWSSERVICE_QNAME, features);
    }

    public MiddlewareWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MiddlewareWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MiddlewareWS
     */
    @WebEndpoint(name = "MiddlewareWSPort")
    public MiddlewareWS getMiddlewareWSPort() {
        return super.getPort(new QName("http://api.middleware.scucrowd.dsg.tuwien.ac.at/", "MiddlewareWSPort"), MiddlewareWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MiddlewareWS
     */
    @WebEndpoint(name = "MiddlewareWSPort")
    public MiddlewareWS getMiddlewareWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.middleware.scucrowd.dsg.tuwien.ac.at/", "MiddlewareWSPort"), MiddlewareWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MIDDLEWAREWSSERVICE_EXCEPTION!= null) {
            throw MIDDLEWAREWSSERVICE_EXCEPTION;
        }
        return MIDDLEWAREWSSERVICE_WSDL_LOCATION;
    }

}
